### ISSUE TITLE
NPM Install

### ISSUE THREAD

**Issue by dinosaw** [dany-on-demand/mn#2]
Heyo! I would love to have this working but having issues with running npm install. I'm using node4 as suggested in the README on Ubuntu.

```
dinosaw@server1:~$ git clone https://github.com/dany-on-demand/mn.git
Cloning into 'mn'...
remote: Counting objects: 38, done.
remote: Total 38 (delta 0), reused 0 (delta 0), pack-reused 38
Unpacking objects: 100% (38/38), done.
dinosaw@server1:~$ cd mn/
dinosaw@server1:~/mn$ node -v
v4.7.0
dinosaw@server1:~/mn$ npm -v
2.15.11
dinosaw@server1:~/mn$ npm install
npm ERR! install Couldn't read dependencies
npm ERR! Linux 3.2.0-54-generic
npm ERR! argv "/home/dinosaw/.nvm/versions/node/v4.7.0/bin/node" "/home/dinosaw/.nvm/versions/node/v4.7.0/bin/npm" "install"
npm ERR! node v4.7.0
npm ERR! npm  v2.15.11
npm ERR! file /home/dinosaw/mn/package.json
npm ERR! code EJSONPARSE
    
npm ERR! Failed to parse json
npm ERR! Unexpected token 'd' at 20:4
npm ERR!   "devDependencies": {
npm ERR!    ^
npm ERR! File: /home/dinosaw/mn/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse
    
npm ERR! Please include the following file with any support request:
npm ERR!     /home/dinosaw/mn/npm-debug.log
```

```
dinosaw@server1:~/mn$ cat /home/dinosaw/mn/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/dinosaw/.nvm/versions/node/v4.7.0/bin/node',
1 verbose cli   '/home/dinosaw/.nvm/versions/node/v4.7.0/bin/npm',
1 verbose cli   'install' ]
2 info using npm@2.15.11
3 info using node@v4.7.0
4 verbose readDependencies loading dependencies from /home/dinosaw/mn/package.json
5 error install Couldn't read dependencies
6 verbose stack Error: Failed to parse json
6 verbose stack Unexpected token 'd' at 20:4
6 verbose stack   "devDependencies": {
6 verbose stack    ^
6 verbose stack     at parseError (/home/dinosaw/.nvm/versions/node/v4.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:390:11)
6 verbose stack     at parseJson (/home/dinosaw/.nvm/versions/node/v4.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:79:23)
6 verbose stack     at /home/dinosaw/.nvm/versions/node/v4.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:48:5
6 verbose stack     at /home/dinosaw/.nvm/versions/node/v4.7.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
6 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
7 verbose cwd /home/dinosaw/mn
8 error Linux 3.2.0-54-generic
9 error argv "/home/dinosaw/.nvm/versions/node/v4.7.0/bin/node" "/home/dinosaw/.nvm/versions/node/v4.7.0/bin/npm" "install"
10 error node v4.7.0
11 error npm  v2.15.11
12 error file /home/dinosaw/mn/package.json
13 error code EJSONPARSE
14 error Failed to parse json
14 error Unexpected token 'd' at 20:4
14 error   "devDependencies": {
14 error    ^
15 error File: /home/dinosaw/mn/package.json
16 error Failed to parse package.json data.
16 error package.json must be actual JSON, not just JavaScript.
16 error
16 error This is not a bug in npm.
16 error Tell the package author to fix their package.json file. JSON.parse
17 verbose exit [ 1, true ]
```

**Comment by dany-on-demand** [comment]
fixed in 5ff5a073be4e8a632af32625d54b135f6f5176d1

**Comment by dany-on-demand** [comment]
what do you want to use it for?

I have a complete re-write of the app that I never finished in koa on an uncommitted branch, I only have a few bugs to fix for feature parity with the express.js version

lemme know if it's something you'd be interested in!

**Comment by dinosaw** [comment]
I would most definitely be interested!

My use of the app is mainly so I can watch video files with friends and family with a self-hosting app on my own server. Rabbit is just all around a pretty awful solution in my opinion, but the idea is great. Plus with yours I see it lets you stream local files (e.g. /media) which is perfect. I don't really see me utilizing the chatting feature, but it's certainly a great option in case it ever is needed.

So yeah, definitely interested. I also haven't heard of koa but just checked out the GitHub and it sounds nice.

Also thanks for the fix, I'll give it a test tomorrow.

**Comment by dinosaw** [comment]
Hello again!

Checking back in (very late) to say I'm still having issues running `npm install`. I cloned the repo with its most recent commit you referenced above, but still basically the same problem.

```
[root@server1 dev]# node -v
v4.7.3
```
```
[root@server1 dev]# git clone https://github.com/dany-on-demand/mn.git && cd mn
Initialized empty Git repository in /home/dinosaw/domains/dinosaw.dev/dev/mn/.git/
remote: Counting objects: 41, done.
remote: Total 41 (delta 0), reused 0 (delta 0), pack-reused 41
Unpacking objects: 100% (41/41), done.
```
```
[root@server1 mn]# npm install
npm ERR! install Couldn't read dependencies
npm ERR! Linux 2.6.32-642.13.1.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v4.7.3/bin/node" "/root/.nvm/versions/node/v4.7.3/bin/npm" "install"
npm ERR! node v4.7.3
npm ERR! npm  v2.15.11
npm ERR! file /home/dinosaw/domains/dinosaw.dev/dev/mn/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 22:3
npm ERR!   }
npm ERR!   ^
npm ERR! File: /home/dinosaw/domains/dinosaw.dev/dev/mn/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dinosaw/domains/dinosaw.dev/dev/mn/npm-debug.log
[root@server1 mn]# cat /home/dinosaw/domains/dinosaw.dev/dev/mn/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v4.7.3/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v4.7.3/bin/npm',
1 verbose cli   'install' ]
2 info using npm@2.15.11
3 info using node@v4.7.3
4 verbose readDependencies loading dependencies from /home/dinosaw/domains/dinosaw.dev/dev/mn/package.json
5 error install Couldn't read dependencies
6 verbose stack Error: Failed to parse json
6 verbose stack Trailing comma in object at 22:3
6 verbose stack   }
6 verbose stack   ^
6 verbose stack     at parseError (/root/.nvm/versions/node/v4.7.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:390:11)
6 verbose stack     at parseJson (/root/.nvm/versions/node/v4.7.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:79:23)
6 verbose stack     at /root/.nvm/versions/node/v4.7.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:48:5
6 verbose stack     at /root/.nvm/versions/node/v4.7.3/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
6 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
7 verbose cwd /home/dinosaw/domains/dinosaw.dev/dev/mn
8 error Linux 2.6.32-642.13.1.el6.x86_64
9 error argv "/root/.nvm/versions/node/v4.7.3/bin/node" "/root/.nvm/versions/node/v4.7.3/bin/npm" "install"
10 error node v4.7.3
11 error npm  v2.15.11
12 error file /home/dinosaw/domains/dinosaw.dev/dev/mn/package.json
13 error code EJSONPARSE
14 error Failed to parse json
14 error Trailing comma in object at 22:3
14 error   }
14 error   ^
15 error File: /home/dinosaw/domains/dinosaw.dev/dev/mn/package.json
16 error Failed to parse package.json data.
16 error package.json must be actual JSON, not just JavaScript.
16 error
16 error This is not a bug in npm.
16 error Tell the package author to fix their package.json file. JSON.parse
17 verbose exit [ 1, true ]
```

Any ideas what's happening?

**Comment by dany-on-demand** [comment]
Hi, sorry, pushed fix now

I played around with rewriting it as a UWP app, I'm not sure where I stand on it now

The koa version is close to something publishable... I just have more pressing stuff first

lemme know when you get it working!

**edit**: did a quick test run and corrected the most grave mistakes I could find, _it works on my setup_ ™

**Comment by dinosaw** [comment]
Hmm still having issues here but it's alright. I don't mind being patient and waiting for the Koa version if you decide to publish that :) Thanks for the help!

**Comment by dany-on-demand** [comment]
try doing a git clone again, works for me:
```bash
D:\Projects\mncopy                                                             
λ git clone https://github.com/dany-on-demand/mn.git .                         
Cloning into '.'...                                                            
remote: Counting objects: 80, done.                                            
remote: Compressing objects: 100% (34/34), done.                               
remote: Total 80 (delta 12), reused 0 (delta 0), pack-reused 44                
Unpacking objects: 100% (80/80), done.                                         
Checking connectivity... done.                                                 
                                                                               
D:\Projects\mncopy (master) (mn@1.0.0)                                         
λ npm i    
Long output...                                      
D:\Projects\mncopy (master) (mn@1.0.0)                                         
λ node server.js                                                               
Go to the generated route (ie localhost:3016/{route}) and enter the password   
                                                                               
route:  6120fd34-5e29-4bec-a898-cd29dd57c224                                   
password: f10db2a9-1f2d-416c-8eea-cd188c740a97                                 
                                                                               
login route: 18bd3cf1-064b-4a6e-a61e-e1fa35c303f0                              
                                                                               
listening on port *:3016                                                       
version a2d7cbe                                                                
                                                                               
^C                                                                             
D:\Projects\mncopy (master) (mn@1.0.0)                                         
λ                                                                              
                                                                               
```

**Comment by dinosaw** [comment]
Hmm, still no go. It's not a huge issue, like I said I don't mind waiting for the new version :) But if you would like to examine the logs (they're kinda long) [here they are](http://pastebin.com/raw/NXTkAYtE).

**Comment by dany-on-demand** [comment]
This isn't an issue with `mn`, you're missing build tools to compile a dependency, try this:
```bash
sudo yum groupinstall 'Development Tools'
```
And run `npm install` again

I don't know why I have utf-8-validate as a dependency, the server seems to run without it... I'll investigate

**Comment by dinosaw** [comment]
I actually have the Development Tools group installed already. But if it's a build tool issue then you're right - nothing to do with your project, just me missing something. I'll look into this and see what my system is needing. Thanks!

**Comment by dany-on-demand** [comment]
Alright this was an extraneous dependency, I have a _slight_ idea how it got in there, it might've been there from the test project I copy-pasted the package json from

I removed it just now

edit:
also moved bufferutils to optional, if node gyp still complains, try `npm install --no-optional`

it's just a performance module, and you don't need performance with a small chat room

**Comment by dinosaw** [comment]
Annnnd boom goes the dynamite! :D It's working for me now bud, thanks for that! So sorry for the back and forth. Installed and running fine on Apache here. Thanks again <3
